backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "Affirmations"
    label: "Affirmations"
    files:
      - file: "src/pages/index.md"
        label: "Affirmations"
        name: "affirmations"
        fields:
          - {label: "Tags", name: "tags", widget: "list"}