backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "Affirmations"
    label: "Affirmations"
    files:
      - file: "data/affirmations.md"
        label: "Affirmations"
        name: "affirmations"
        fields:
          - {label: "affirmations", name: "affirmations", widget: "list", fields: [
            {name: 'main', widget: 'text'}
          ]}
          - {name: "password", widget: string}